default:
  tags:
    - docker
    - ubuntu

  image: "nexus.nic.etu:8181/nic/fedora_36:base"

stages:
  - test

unit_tests:
  stage: test
  script:
    - dnf update -y && dnf install -y python3 python3-pip protobuf-compiler rabbitmq-server
    - systemctl start rabbitmq-server
    - systemctl enable rabbitmq-server
    - pip3 install -r ./client/requirements.txt
    - pip3 install -r ./server/requirements.txt
    - python3 ./client/setup.py build
    - python3 ./server/setup.py build
    - python3 -m unittest discover tests
