default:
  tags:
    - docker
    - ubuntu

  image: "nexus.nic.etu:8181/nic/fedora_36:base"

stages:
  - test

unit_tests:
  stage: test
  services:
    - name: rabbitmq:3.11-management
      alias: rabbitmq
  variables:
    RABBITMQ_HOST: rabbitmq
    RABBITMQ_PORT: 5672
  script:
    - dnf update -y && dnf install -y python3 python3-pip protobuf-compiler python3-qt5

    - pip3 install -r ./client/requirements.txt
    - pip3 install -r ./server/requirements.txt

    - protoc -I=./server/rabbitmq_server/protobuf --python_out=./server/rabbitmq_server/protobuf ./server/rabbitmq_server/protobuf/message.proto
    - protoc -I=./client/rabbitmq_client/protobuf --python_out=./client/rabbitmq_client/protobuf ./client/rabbitmq_client/protobuf/message.proto

    - mkdir -p client/rabbitmq_client/client_gui
    - pyuic5 client/clientUI/clientGUI.ui -o client/rabbitmq_client/client_gui/main_window_ui.py
    - pyuic5 client/clientUI/settingsGUI.ui -o client/rabbitmq_client/client_gui/settings_dialog_ui.py

    - python3 ./client/setup.py build
    - python3 ./server/setup.py build

    - python3 -m unittest discover client/tests
    - python3 -m unittest discover server/tests
