# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client/clientUI/clientGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 615)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.loggingText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.loggingText.setReadOnly(True)
        self.loggingText.setObjectName("loggingText")
        self.gridLayout_3.addWidget(self.loggingText, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.requestSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.requestSpinBox.setMinimum(-999999999)
        self.requestSpinBox.setMaximum(999999999)
        self.requestSpinBox.setObjectName("requestSpinBox")
        self.gridLayout.addWidget(self.requestSpinBox, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.delaySpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.delaySpinBox.setObjectName("delaySpinBox")
        self.horizontalLayout_2.addWidget(self.delaySpinBox)
        self.useDelayCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.useDelayCheckBox.setObjectName("useDelayCheckBox")
        self.horizontalLayout_2.addWidget(self.useDelayCheckBox)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.sendRequestButton = QtWidgets.QPushButton(self.groupBox)
        self.sendRequestButton.setObjectName("sendRequestButton")
        self.sendRequestButton.setEnabled(False)
        self.gridLayout.addWidget(self.sendRequestButton, 3, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.groupBox_2)
        self.cancelButton.setEnabled(False)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout_2.addWidget(self.cancelButton, 2, 2, 1, 1)
        self.serverStateLabel = QtWidgets.QLabel(self.groupBox_2)
        self.serverStateLabel.setObjectName("serverStateLabel")
        self.gridLayout_2.addWidget(self.serverStateLabel, 2, 1, 1, 1)
        self.serverResponseLabel = QtWidgets.QLabel(self.groupBox_2)
        self.serverResponseLabel.setObjectName("serverResponseLabel")
        self.gridLayout_2.addWidget(self.serverResponseLabel, 4, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.settingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingsButton.setObjectName("settingsButton")
        self.gridLayout_3.addWidget(self.settingsButton, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Текущий запрос"))
        self.label.setText(_translate("MainWindow", "Число:"))
        self.label_2.setText(_translate("MainWindow", "Время обработки запроса на сервере, сек:"))
        self.useDelayCheckBox.setText(_translate("MainWindow", "Задействовать"))
        self.sendRequestButton.setText(_translate("MainWindow", "Отправить"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Состояние обработки запроса"))
        self.label_5.setText(_translate("MainWindow", "Ответ сервера:"))
        self.label_3.setText(_translate("MainWindow", "Состояние:"))
        self.cancelButton.setText(_translate("MainWindow", "Отмена"))
        self.serverStateLabel.setText(_translate("MainWindow", "состояние"))
        self.serverResponseLabel.setText(_translate("MainWindow", "ответ сервера"))
        self.settingsButton.setText(_translate("MainWindow", "Настройки"))
